### ISSUE TITLE
Missing Update Function

### ISSUE THREAD

**Issue by djeraseit** [gavinggordon/wordstore#2]
Should be able to update parameters if word is there. Thanks again for wonderful class.

**Comment by gavinggordon** [comment]
I appreciate your feedback! 

Keep your eye out, over the next couple of days, for more updates I will be releasing,
which will include, but is not limited to, added functions (i.e., Update, Delete ).

**Comment by gavinggordon** [comment]
Hello.

Version 1.1.1 addresses your request for the ability to update; I have added the 'update' method.

I am having quite some difficulty, however, adding the ability to delete, via a 'delete' method.
Once I have found a solution, though, I will let you know.

**Comment by gavinggordon** [comment]
Version 2.0.4 has been released; this version provides much more capability, as it is CRUD compliant.
