### ISSUE TITLE
Composer Update

### ISSUE THREAD

**Issue by djeraseit** [gavinggordon/wordstore#3]
Problem 1
    - The requested package gavinggordon/wordstore 1.1.1 exists as gavinggordon/wordstore[1.0.0, dev-master] but those are rejected by your constraint.

Is this correct?

**Comment by gavinggordon** [comment]
Hello. 

I believe I have resolved the issue. Try again; let me know if you continue to experience issues. 😊

**Comment by gavinggordon** [comment]
I have just released version 2.0.4 which addressed a number of issues, in addition to the added benefits of being CRUD compliant.
